services:
  jia-hui-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_MODE: production
    image: jia-hui-web:latest
    container_name: jia-hui-web
    ports:
      - "8080:80"
    restart: unless-stopped
