services:
  jia-hui-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: jia-hui-web:latest
    container_name: jia-hui-web
    ports:
      - "8080:80"
    restart: unless-stopped
